### ISSUE TITLE
immutable.js getIn doesn't work

### ISSUE THREAD

**Issue by localhosted** [ellbee/redux-boilerplate#3]
For some reason getIn(), won't work in selectors, only if copying the state into a new immutable. Same thing for setIn().

[Here is the same project reproducing the bug.](http://wikisend.com/download/219762/redux-boilerplate.zip)

**Comment by ellbee** [comment]
Hey @localhosted, Immutable.Map() only converts the outer map to an Immutable value so the `getIn` property is actually a plain javascript object. If you use Immutable.fromJS() it will work. 

``` js
const initialState = Immutable.fromJS({name: 'Turtle', getIn: {test: "super empty"}});
```
