### ISSUE TITLE
Devtools reset and revert fails

### ISSUE THREAD

**Issue by luandro** [ellbee/redux-boilerplate#4]
```
Warning: Failed propType: Required prop `location` was not specified in `RoutingContext`.
```

**Comment by ellbee** [comment]
Yep, I have been getting the same thing. I think it is due to [this redux-router issue](https://github.com/rackt/redux-router/issues/67). I am going to look into it further, but to workaround it for now I have been committing immediately and then using revert rather than reset.

**Comment by ellbee** [comment]
I have switched to redux-simple-router because I like it. A nice side effect is that it fixed this bug.

**Comment by luandro** [comment]
I've switched in my own boilerplate as well :+1:
